### ISSUE TITLE
Feature request: Shadow takes into account rotation of parent 

### ISSUE THREAD

**Issue by jamescoats** [TABmk/godot-2d-shadow-shader#2]
Would love to have the ability of the parent to rotate, while the shadow rotates around its centre rather than that of the parent. It may have to be passed shader parameters of parent rotation and centre of rotation?

**Comment by TABmk** [comment]
Hi, @jamescoats , I have just updated the shader to v2 with some breaking changes. You can check the updated code here: https://github.com/TABmk/godot-2d-shadow-shader/blob/master/shadow.gdshader

Soon, I will update the documentation. The shadow now stays at its own position by default. You can revert to the old version by toggling the "Disable Rotating" parameter.

**Comment by jamescoats** [comment]
Amazing, thank you!
